package PanyaUI;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author dqh
 */
public class TestMain extends javax.swing.JFrame {

    /** Creates new form TestMain */
    public TestMain() {
        initComponents();
    }

    /**
     * Create new form with custom color palette
     * @param themeName name of a theme, derived from Theme.THEME_NAMES
     */
    public TestMain(String themeName) {
        initComponents();
        initTheme(themeName);
        highlightLabelColor(HomeLabel);
    }

    public TestMain(String themeName, boolean b) {
        initComponents();
        this.PRIDE = b;
        initTheme(themeName);
        highlightLabelColor(HomeLabel);
    }

    public TestMain(Color primary, Color light, Color dark){
        initComponents();
        initTheme(primary, light, dark);
        highlightLabelColor(HomeLabel);
    }

    public void initTheme(Color primary, Color light, Color dark){
        if (primary == null || light == null || dark == null){
            return;
        }

        final var PRIMARY = primary;
        final var LIGHT = light;
        final var DARK = dark;

        final var PRIMARY_TEXT = Theme.textColorFromBackgroundColor(PRIMARY);
        final var LIGHT_TEXT = Theme.textColorFromBackgroundColor(LIGHT);
        final var DARK_TEXT = Theme.textColorFromBackgroundColor(DARK);

        this.HIGHLIGHT_LABEL_COLOR = PRIMARY;
        this.HIGHLIGHT_TEXT_LABEL_COLOR = PRIMARY_TEXT;
        this.DEFAULT_LABEL_COLOR = LIGHT;
        this.DEFAULT_TEXT_LABEL_COLOR = LIGHT_TEXT;

        //MainPannel.setBackground(PRIMARY);
        Section.setBackground(LIGHT);
        
        HeaderContent.setBackground(PRIMARY);
        HeaderContentLabel.setForeground(PRIMARY_TEXT);

        //Header.setBackground(PRIMARY);

        HomeContent.setForeground(PRIMARY_TEXT);
        HomeLabel.setBackground(LIGHT);
        HomeLabel.setForeground(LIGHT_TEXT);

        MenuContent.setForeground(PRIMARY_TEXT);
        MenuLabel.setBackground(LIGHT);
        MenuLabel.setForeground(LIGHT_TEXT); 

        RecipeContent.setForeground(PRIMARY_TEXT);
        RecipeLabel.setBackground(LIGHT);
        RecipeLabel.setForeground(LIGHT_TEXT);

        SettingsContent.setForeground(PRIMARY_TEXT);
        SettingsLabel.setBackground(LIGHT); 
        SettingsLabel.setForeground(LIGHT_TEXT);
        
        StorageContent.setForeground(PRIMARY_TEXT);
        StorageLabel.setBackground(LIGHT);
        StorageLabel.setForeground(LIGHT_TEXT);

        Title.setBackground(DARK); 
        TitleLabel.setForeground(DARK_TEXT); 
    }

    public void initTheme(String themeName){
        var theme = new Theme().getTheme(themeName);
        if (theme == null){
            return;
        }

        final var PRIMARY = theme.get(Theme.PRIMARY);
        final var LIGHT = theme.get(Theme.LIGHT);
        final var DARK = theme.get(Theme.DARK);
    
        this.initTheme(PRIMARY, LIGHT, DARK);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MainPannel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Title = new javax.swing.JPanel();
        HeaderContent = new javax.swing.JPanel();
        HeaderContentLabel = new javax.swing.JLabel();
        Section = new javax.swing.JPanel();
        HomeLabel = new javax.swing.JLabel();
        MenuLabel = new javax.swing.JLabel();
        StorageLabel = new javax.swing.JLabel();
        RecipeLabel = new javax.swing.JLabel();
        SettingsLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        HomeContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MenuContent = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        StorageContent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        RecipeContent = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SettingsContent = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setBackground(new java.awt.Color(0, 96, 15));

        HeaderContent.setBackground(new java.awt.Color(56, 142, 60));

        HeaderContentLabel.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        HeaderContentLabel.setText("Home screen content");

        Section.setBackground(new java.awt.Color(118, 210, 117));

        HomeLabel.setBackground(new java.awt.Color(56, 142, 60));
        HomeLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        HomeLabel.setForeground(java.awt.Color.white);
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("Home");
        HomeLabel.setOpaque(true);
        HomeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLabelMouseClicked(evt);
            }
        });

        MenuLabel.setBackground(new java.awt.Color(118, 210, 117));
        MenuLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        MenuLabel.setForeground(java.awt.Color.darkGray);
        MenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuLabel.setText("Menu");
        MenuLabel.setOpaque(true);
        MenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLabelMouseClicked(evt);
            }
        });

        StorageLabel.setBackground(new java.awt.Color(118, 210, 117));
        StorageLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        StorageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StorageLabel.setText("Storage");
        StorageLabel.setOpaque(true);
        StorageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StorageLabelMouseClicked(evt);
            }
        });

        RecipeLabel.setBackground(new java.awt.Color(118, 210, 117));
        RecipeLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        RecipeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecipeLabel.setText("Recipe");
        RecipeLabel.setOpaque(true);
        RecipeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecipeLabelMouseClicked(evt);
            }
        });

        SettingsLabel.setBackground(new java.awt.Color(118, 210, 117));
        SettingsLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        SettingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SettingsLabel.setText("Settings");
        SettingsLabel.setOpaque(true);
        SettingsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsLabelMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout SectionLayout = new org.jdesktop.layout.GroupLayout(Section);
        Section.setLayout(SectionLayout);
        SectionLayout.setHorizontalGroup(
            SectionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SectionLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(HomeLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(MenuLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(StorageLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(RecipeLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(SettingsLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        SectionLayout.setVerticalGroup(
            SectionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(HomeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .add(MenuLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(StorageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(RecipeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(SettingsLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout HeaderContentLayout = new org.jdesktop.layout.GroupLayout(HeaderContent);
        HeaderContent.setLayout(HeaderContentLayout);
        HeaderContentLayout.setHorizontalGroup(
            HeaderContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(HeaderContentLayout.createSequentialGroup()
                .add(32, 32, 32)
                .add(HeaderContentLabel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(Section, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderContentLayout.setVerticalGroup(
            HeaderContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(HeaderContentLayout.createSequentialGroup()
                .add(53, 53, 53)
                .add(HeaderContentLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 50, Short.MAX_VALUE)
                .add(Section, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        TitleLabel.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        TitleLabel.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        TitleLabel.setText("Pan-ya");

        org.jdesktop.layout.GroupLayout TitleLayout = new org.jdesktop.layout.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, HeaderContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(TitleLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(TitleLabel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, TitleLayout.createSequentialGroup()
                .addContainerGap()
                .add(TitleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(HeaderContent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        Content.setLayout(new java.awt.CardLayout());

        HomeContent.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel2.setText("HOME CONTENT");

        org.jdesktop.layout.GroupLayout HomeContentLayout = new org.jdesktop.layout.GroupLayout(HomeContent);
        HomeContent.setLayout(HomeContentLayout);
        HomeContentLayout.setHorizontalGroup(
            HomeContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, HomeContentLayout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .add(jLabel2)
                .add(382, 382, 382))
        );
        HomeContentLayout.setVerticalGroup(
            HomeContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(HomeContentLayout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jLabel2)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        Content.add(HomeContent, "card2");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel3.setText("MENU CONTENT");

        org.jdesktop.layout.GroupLayout MenuContentLayout = new org.jdesktop.layout.GroupLayout(MenuContent);
        MenuContent.setLayout(MenuContentLayout);
        MenuContentLayout.setHorizontalGroup(
            MenuContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, MenuContentLayout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .add(jLabel3)
                .add(346, 346, 346))
        );
        MenuContentLayout.setVerticalGroup(
            MenuContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MenuContentLayout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jLabel3)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        Content.add(MenuContent, "card2");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel4.setText("STORAGE CONTENT");

        org.jdesktop.layout.GroupLayout StorageContentLayout = new org.jdesktop.layout.GroupLayout(StorageContent);
        StorageContent.setLayout(StorageContentLayout);
        StorageContentLayout.setHorizontalGroup(
            StorageContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, StorageContentLayout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .add(jLabel4)
                .add(346, 346, 346))
        );
        StorageContentLayout.setVerticalGroup(
            StorageContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(StorageContentLayout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jLabel4)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        Content.add(StorageContent, "card2");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel5.setText("RECIPE CONTENT");

        org.jdesktop.layout.GroupLayout RecipeContentLayout = new org.jdesktop.layout.GroupLayout(RecipeContent);
        RecipeContent.setLayout(RecipeContentLayout);
        RecipeContentLayout.setHorizontalGroup(
            RecipeContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RecipeContentLayout.createSequentialGroup()
                .add(387, 387, 387)
                .add(jLabel5)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        RecipeContentLayout.setVerticalGroup(
            RecipeContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RecipeContentLayout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jLabel5)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        Content.add(RecipeContent, "card5");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel6.setText("SETTINGS CONTENT");

        org.jdesktop.layout.GroupLayout SettingsContentLayout = new org.jdesktop.layout.GroupLayout(SettingsContent);
        SettingsContent.setLayout(SettingsContentLayout);
        SettingsContentLayout.setHorizontalGroup(
            SettingsContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, SettingsContentLayout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .add(jLabel6)
                .add(346, 346, 346))
        );
        SettingsContentLayout.setVerticalGroup(
            SettingsContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SettingsContentLayout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jLabel6)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        Content.add(SettingsContent, "card2");

        org.jdesktop.layout.GroupLayout HeaderLayout = new org.jdesktop.layout.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(Content, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(HeaderLayout.createSequentialGroup()
                .add(Title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Content, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout MainPannelLayout = new org.jdesktop.layout.GroupLayout(MainPannel);
        MainPannel.setLayout(MainPannelLayout);
        MainPannelLayout.setHorizontalGroup(
            MainPannelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Header, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPannelLayout.setVerticalGroup(
            MainPannelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainPannelLayout.createSequentialGroup()
                .add(Header, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainPannel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainPannel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setHomeHeaderContent(){
        this.HeaderContentLabel.setText("Pan-ya home page");
    }

    void setMenuHeaderContent(){
        this.HeaderContentLabel.setText("Menu page, please choose your option");
    }
    void setStorageHeaderContent(){
        this.HeaderContentLabel.setText("Storage page, ストレンジ");
    }
    
    private void SettingsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsLabelMouseClicked
        setSettingsHeaderContent();

        defaultLabelColor(this.HomeLabel);
        defaultLabelColor(this.StorageLabel);
        defaultLabelColor(this.MenuLabel);
        defaultLabelColor(this.RecipeLabel);
        highlightLabelColor(this.SettingsLabel);

        this.HomeContent.setVisible(false);
        this.MenuContent.setVisible(false);
        this.RecipeContent.setVisible(true);
        this.SettingsContent.setVisible(false);
        this.StorageContent.setVisible(false);
    }//GEN-LAST:event_SettingsLabelMouseClicked

    private void RecipeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecipeLabelMouseClicked
        setRecipeHeaderContent();

        defaultLabelColor(this.HomeLabel);
        defaultLabelColor(this.StorageLabel);
        defaultLabelColor(this.MenuLabel);
        defaultLabelColor(this.SettingsLabel);
        highlightLabelColor(this.RecipeLabel);

        this.HomeContent.setVisible(false);
        this.MenuContent.setVisible(false);
        this.RecipeContent.setVisible(true);
        this.SettingsContent.setVisible(false);
        this.StorageContent.setVisible(false);
    }//GEN-LAST:event_RecipeLabelMouseClicked

    private void StorageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StorageLabelMouseClicked
        setStorageHeaderContent();

        defaultLabelColor(this.HomeLabel);
        defaultLabelColor(this.MenuLabel);
        defaultLabelColor(this.RecipeLabel);
        defaultLabelColor(this.SettingsLabel);
        highlightLabelColor(this.StorageLabel);

        this.HomeContent.setVisible(false);
        this.MenuContent.setVisible(false);
        this.RecipeContent.setVisible(false);
        this.SettingsContent.setVisible(false);
        this.StorageContent.setVisible(true);
    }//GEN-LAST:event_StorageLabelMouseClicked

    private void MenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLabelMouseClicked
        setMenuHeaderContent();

        defaultLabelColor(this.HomeLabel);
        defaultLabelColor(this.RecipeLabel);
        defaultLabelColor(this.SettingsLabel);
        defaultLabelColor(this.StorageLabel);
        highlightLabelColor(this.MenuLabel);

        this.HomeContent.setVisible(false);
        this.MenuContent.setVisible(true);
        this.RecipeContent.setVisible(false);
        this.SettingsContent.setVisible(false);
        this.StorageContent.setVisible(false);
    }//GEN-LAST:event_MenuLabelMouseClicked

    private void HomeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLabelMouseClicked
        setHomeHeaderContent();

        highlightLabelColor(this.HomeLabel);
        defaultLabelColor(this.MenuLabel);
        defaultLabelColor(this.RecipeLabel);
        defaultLabelColor(this.SettingsLabel);
        defaultLabelColor(this.StorageLabel);

        this.HomeContent.setVisible(true);
        this.MenuContent.setVisible(false);
        this.RecipeContent.setVisible(false);
        this.SettingsContent.setVisible(false);
        this.StorageContent.setVisible(false);

    }//GEN-LAST:event_HomeLabelMouseClicked
    
    void setRecipeHeaderContent(){
        this.HeaderContentLabel.setText("Recipe page, 料理公式");
    }
    
    void setSettingsHeaderContent(){
        this.HeaderContentLabel.setText("Settings page, 設定");
    }
    
    private void highlightLabelColor(JLabel lbl){
        if (PRIDE){
            initTheme(Theme.getRandomThemeName());
        }
        lbl.setBackground(HIGHLIGHT_LABEL_COLOR);
        lbl.setForeground(HIGHLIGHT_TEXT_LABEL_COLOR);
    }
    private void defaultLabelColor(JLabel lbl){
        lbl.setBackground(DEFAULT_LABEL_COLOR);
        lbl.setForeground(DEFAULT_TEXT_LABEL_COLOR);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("foo".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
           
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestMain().setVisible(true);
            }
        });
    }

    Color HIGHLIGHT_TEXT_LABEL_COLOR = Color.WHITE;
    Color DEFAULT_TEXT_LABEL_COLOR = Color.BLACK;
    Color HIGHLIGHT_LABEL_COLOR = new Color(56, 142, 60);
    Color DEFAULT_LABEL_COLOR = new Color(118, 210, 117);
    
    boolean PRIDE = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HeaderContent;
    private javax.swing.JLabel HeaderContentLabel;
    private javax.swing.JPanel HomeContent;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JPanel MainPannel;
    private javax.swing.JPanel MenuContent;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JPanel RecipeContent;
    private javax.swing.JLabel RecipeLabel;
    private javax.swing.JPanel Section;
    private javax.swing.JPanel SettingsContent;
    private javax.swing.JLabel SettingsLabel;
    private javax.swing.JPanel StorageContent;
    private javax.swing.JLabel StorageLabel;
    private javax.swing.JPanel Title;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
